name: Lint and build

on:
  workflow_dispatch:

jobs:
  lint-and-build:
    strategy:
      matrix:
        target: [ui, api]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint
      - name: Bundle sources
        run: npm run build:${{ matrix.target }}
